DROP TABLE AREAHD, ALUNOAULA1, ADMINISTRADORHD, ASSOCIADOAUX, ASSOCIADOEX, CHAMADOHD, 
CIDADE, CIDADEEX, CLIENTE, CLIENTEHD, CURSOAULA1, DEPARTAMENTO,EMPREGADO, ESTOQUEEX,
GERENTEHD, MATERIAL, OPERADORHD, PEDIDO, PEDIDOITEM, PRODUTO, PRODUTOEX, PRODUTOMATERIAL,
REGISTROHD, SERVICOHD;
