SELECT IDPEDIDO, IDCLIENTE, DATAPEDIDO, VALORPEDIDO, SITUACAO FROM PEDIDO WHERE situacao = 'A' 
AND idcliente = 11518 OR valorpedido > 9000 ORDER BY valorpedido;

SELECT * FROM MATERIAL WHERE PESOLIQUIDO > 4 AND precocusto < 0.3;

SELECT distinct nome, uf from cidade where uf = 'RS' ORDER BY NOME;

SELECT * FROM pedido WHERE valorpedido = 28299.76 AND situacao = 'Q';
SELECT * FROM PEDIDO WHERE IDPEDIDO = 162;

SELECT * FROM CLIENTE WHERE CEP IS NULL AND SITUACAO = 'A';

SELECT IDPEDIDO, QUANTIDADE * PRECOUNITARIO AS VALORTOTAL, IDPRODUTO 
FROM PEDIDOITEM where idpedido = 168 ORDER BY QUANTIDADE * PRECOUNITARIO DESC;

SELECT * FROM MATERIAL WHERE PESOLIQUIDO >= 0.5 AND PESOLIQUIDO <= 0.6;





SELECT * FROM PEDIDO WHERE (SITUACAO = 'A' OR SITUACAO = 'C' OR SITUACAO = 'I') AND VALORPEDIDO >= 9800;


/*
NÃO FIZ O CODIGO DA 8 E 9
*/
